#!/usr/bin/env kubectl apply -f
apiVersion: v1
kind: ConfigMap
metadata:
  name: om-director-data
data:
  director_config.yaml: |
    logging:
      format: text
      level: debug
      source: false

    debug:
      maxSends: 0
      maxMatchesPerSend: 0
      sleepBetweenSendsSeconds: 30

    agones:
      namespace: default
      fleetName: udp-server
      generateName: udp-server-

  ###

  profile.json: |
    {
      "id": "partial",
      "name": "partialv1",
      "hostname": "om-function",
      "port": 50502,
      "properties": {
        "pools": [
        {
          "name": "defaultPool",
          "filters": [
          { "name": "mmr.rating", "attribute": "mmr.rating", "minv": "0" }
          ]
        }
        ],
        "rosters": [
        {
          "name": "red",
          "players": [
          { "pool": "defaultPool" }
          ]
        },
        {
          "name": "blue",
          "players": [
          { "pool": "defaultPool" }
          ]
        }
        ]
      }
    }